# Generated by Django 5.0.6 on 2024-06-22 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
    ]
